In [1]:
import sys, os

def find_project_root(marker='requirements.txt'):
    path = os.getcwd()
    while path != os.path.dirname(path):
        if os.path.exists(os.path.join(path, marker)):
            return path
        path = os.path.dirname(path)
    raise FileNotFoundError(f"Could not find project root (looked for {marker})")

project_root = find_project_root()
if project_root not in sys.path:
    sys.path.append(project_root)

print(project_root)

e:\DigitalFutureProjects\TrainingProjects\standalone-data-rag-assistant

In [2]:
import pandas as pd
import sqlite3
import os
import numpy as np

notebook_dir = os.getcwd()

project_root = os.path.dirname(
    os.path.dirname(notebook_dir)
)

file_path = os.path.join(
    project_root,
    'data',
    'raw',
    'week3',
    'retail_store_sales.csv'
)

df = pd.read_csv(file_path, encoding='windows-1252')

df.info()
print(df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB
(12575, 11)

In [3]:
print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDuplicate Transaction IDs:")
print(df["Transaction ID"].duplicated().sum())

Missing values:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

Duplicate rows:
0

Duplicate Transaction IDs:
0

In [4]:
print("\nUnique values:")
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:")
    print(df[col].unique()[:20])

Unique values:

Transaction ID:
<StringArray>
['TXN_6867343', 'TXN_3731986', 'TXN_9303719', 'TXN_9458126', 'TXN_4575373',
 'TXN_7482416', 'TXN_3652209', 'TXN_1372952', 'TXN_9728486', 'TXN_2722661',
 'TXN_8776416', 'TXN_5422631', 'TXN_5874772', 'TXN_4413070', 'TXN_2490363',
 'TXN_1809665', 'TXN_7563311', 'TXN_9634894', 'TXN_4396807', 'TXN_4206593']
Length: 20, dtype: str

Customer ID:
<StringArray>
['CUST_09', 'CUST_22', 'CUST_02', 'CUST_06', 'CUST_05', 'CUST_07', 'CUST_21',
 'CUST_23', 'CUST_25', 'CUST_14', 'CUST_15', 'CUST_17', 'CUST_01', 'CUST_10',
 'CUST_04', 'CUST_13', 'CUST_18', 'CUST_08', 'CUST_20', 'CUST_12']
Length: 20, dtype: str

Category:
<StringArray>
[                        'Patisserie',                      'Milk Products',
                           'Butchers',                          'Beverages',
                               'Food',                          'Furniture',
      'Electric household essentials', 'Computers and electric accessories']
Length: 8, dtype: str

Item:
<StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',            nan,  'Item_1_FOOD',  'Item_16_FUR',
  'Item_22_BUT',   'Item_3_BUT',  'Item_2_FOOD',  'Item_24_PAT',
 'Item_16_MILK',  'Item_17_PAT',  'Item_13_EHE',   'Item_7_BEV',
   'Item_4_EHE', 'Item_10_FOOD',  'Item_14_FUR',  'Item_20_BUT']
Length: 20, dtype: str

Payment Method:
<StringArray>
['Digital Wallet', 'Credit Card', 'Cash']
Length: 3, dtype: str

Location:
<StringArray>
['Online', 'In-store']
Length: 2, dtype: str

Transaction Date:
<StringArray>
['2024-04-08', '2023-07-23', '2022-10-05', '2022-05-07', '2022-10-02',
 '2023-11-30', '2023-06-10', '2024-04-02', '2023-04-26', '2024-03-14',
 '2024-12-14', '2025-01-12', '2023-09-09', '2022-05-20', '2022-05-22',
 '2022-05-11', '2024-11-16', '2022-04-17', '2022-02-07', '2025-01-13']
Length: 20, dtype: str

Discount Applied:
[True False nan]

C:\Users\salha\AppData\Local\Temp\ipykernel_20056\2525108748.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [5]:
print(df.describe(include="all"))

       Transaction ID Customer ID   Category        Item  Price Per Unit  \
count           12575       12575      12575       11362    11966.000000
unique          12575          25          8         200             NaN
top       TXN_6867343     CUST_05  Furniture  Item_2_BEV             NaN
freq                1         544       1591         126             NaN
mean              NaN         NaN        NaN         NaN       23.365912
std               NaN         NaN        NaN         NaN       10.743519
min               NaN         NaN        NaN         NaN        5.000000
25%               NaN         NaN        NaN         NaN       14.000000
50%               NaN         NaN        NaN         NaN       23.000000
75%               NaN         NaN        NaN         NaN       33.500000
max               NaN         NaN        NaN         NaN       41.000000

            Quantity   Total Spent Payment Method Location Transaction Date  \
count   11971.000000  11971.000000          12575    12575            12575
unique           NaN           NaN              3        2             1114
top              NaN           NaN           Cash   Online       2022-05-30
freq             NaN           NaN           4310     6354               26
mean        5.536380    129.652577            NaN      NaN              NaN
std         2.857883     94.750697            NaN      NaN              NaN
min         1.000000      5.000000            NaN      NaN              NaN
25%         3.000000     51.000000            NaN      NaN              NaN
50%         6.000000    108.500000            NaN      NaN              NaN
75%         8.000000    192.000000            NaN      NaN              NaN
max        10.000000    410.000000            NaN      NaN              NaN

       Discount Applied
count              8376
unique                2
top                True
freq               4219
mean                NaN
std                 NaN
min                 NaN
25%                 NaN
50%                 NaN
75%                 NaN
max                 NaN

In [6]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [7]:
for col in ["Category", "Item", "Payment Method", "Location"]:
    print(col)
    print(df[col].value_counts(dropna=False))

Category
Category
Furniture                             1591
Electric household essentials         1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64
Item
Item
NaN             1213
Item_2_BEV       126
Item_25_FUR      113
Item_11_FUR      110
Item_16_MILK     109
                ...
Item_13_BEV        7
Item_5_BEV         7
Item_13_FUR        7
Item_21_PAT        6
Item_3_EHE         5
Name: count, Length: 201, dtype: int64
Payment Method
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64
Location
Location
Online      6354
In-store    6221
Name: count, dtype: int64

In [8]:
print("Negative or Zero Quantity:", (df["Quantity"] <= 0).sum())
print("Negative or Zero Price:", (df["Price Per Unit"] <= 0).sum())
print("Negative Total Spent:", (df["Total Spent"] < 0).sum())

Negative or Zero Quantity: 0
Negative or Zero Price: 0
Negative Total Spent: 0

In [9]:
Q1 = df['Total Spent'].quantile(0.25)
Q3 = df['Total Spent'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers = df[df['Total Spent'] > upper_bound]
print(f"Number of statistical outliers in Total Spent: {len(outliers)}")

display(outliers.head(10))

Number of statistical outliers in Total Spent: 60

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
27,TXN_1599706,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2024-03-24,True
133,TXN_2953434,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2023-08-10,NaN
339,TXN_4374445,CUST_12,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2024-10-17,NaN
869,TXN_1814138,CUST_06,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2024-11-16,NaN
1060,TXN_3710081,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2023-08-12,NaN
1088,TXN_1273334,CUST_22,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2022-11-04,True
1468,TXN_1938135,CUST_17,Butchers,Item_25_BUT,41.0,10.0,410.0,Digital Wallet,In-store,2023-12-20,True
1505,TXN_8520397,CUST_12,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Credit Card,Online,2024-03-27,True
1568,TXN_8048041,CUST_14,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2023-12-25,True
1950,TXN_1860120,CUST_01,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2022-01-19,True

In [10]:
discounted_rows = df[
    (df['Discount Applied'] == True) & 
    df['Quantity'].notna() & 
    df['Price Per Unit'].notna() & 
    df['Total Spent'].notna()
]

expected = discounted_rows['Quantity'] * discounted_rows['Price Per Unit']
ratios = (discounted_rows['Total Spent'] / expected).round(2)

print("Discount Multipliers Distribution:")
print(ratios.value_counts())

Discount Multipliers Distribution:
1.0    3801
Name: count, dtype: int64

In [11]:
complete_financials = df[
    df['Quantity'].notna() & 
    df['Price Per Unit'].notna() & 
    df['Total Spent'].notna()
]

expected_all = complete_financials['Quantity'] * complete_financials['Price Per Unit']
ratios_all = (complete_financials['Total Spent'] / expected_all).round(2)

print("Multipliers across ALL complete rows (True, False, and Null):")
print(ratios_all.value_counts())

Multipliers across ALL complete rows (True, False, and Null):
1.0    11362
Name: count, dtype: int64

In [12]:
price_by_discount = df.groupby(['Item', 'Discount Applied'])['Price Per Unit'].mean().unstack()
print(price_by_discount.head(50))

Discount Applied  False  True
Item
Item_10_BEV        18.5   18.5
Item_10_BUT        18.5   18.5
Item_10_CEA        18.5   18.5
Item_10_EHE        18.5   18.5
Item_10_FOOD       18.5   18.5
Item_10_FUR        18.5   18.5
Item_10_MILK       18.5   18.5
Item_10_PAT        18.5   18.5
Item_11_BEV        20.0   20.0
Item_11_BUT        20.0   20.0
Item_11_CEA        20.0   20.0
Item_11_EHE        20.0   20.0
Item_11_FOOD       20.0   20.0
Item_11_FUR        20.0   20.0
Item_11_MILK       20.0   20.0
Item_11_PAT        20.0   20.0
Item_12_BEV        21.5   21.5
Item_12_BUT        21.5   21.5
Item_12_CEA        21.5   21.5
Item_12_EHE        21.5   21.5
Item_12_FOOD       21.5   21.5
Item_12_FUR        21.5   21.5
Item_12_MILK       21.5   21.5
Item_12_PAT        21.5   21.5
Item_13_BEV        23.0   23.0
Item_13_BUT        23.0   23.0
Item_13_CEA        23.0   23.0
Item_13_EHE        23.0   23.0
Item_13_FOOD       23.0   23.0
Item_13_FUR        23.0   23.0
Item_13_MILK       23.0   23.0
Item_13_PAT        23.0   23.0
Item_14_BEV        24.5   24.5
Item_14_BUT        24.5   24.5
Item_14_CEA        24.5   24.5
Item_14_EHE         NaN   24.5
Item_14_FOOD       24.5   24.5
Item_14_FUR        24.5   24.5
Item_14_MILK       24.5   24.5
Item_14_PAT        24.5   24.5
Item_15_BEV        26.0   26.0
Item_15_BUT        26.0   26.0
Item_15_CEA        26.0   26.0
Item_15_EHE        26.0   26.0
Item_15_FOOD       26.0   26.0
Item_15_FUR        26.0   26.0
Item_15_MILK       26.0   26.0
Item_15_PAT        26.0   26.0
Item_16_BEV        27.5   27.5
Item_16_BUT        27.5   27.5

In [13]:
categorical_cols = ["Category", "Payment Method", "Location"]

print("--- Hidden Whitespace Audit ---")
for col in categorical_cols:
    hidden_spaces_count = (df[col].dropna() != df[col].dropna().str.strip()).sum()
    print(f"{col}: {hidden_spaces_count} rows with hidden spaces")

--- Hidden Whitespace Audit ---
Category: 0 rows with hidden spaces
Payment Method: 0 rows with hidden spaces
Location: 0 rows with hidden spaces

In [14]:
mapping_check = (
    df.dropna(subset=["Item", "Category", "Price Per Unit"])
      .groupby(["Category", "Price Per Unit"])["Item"]
      .nunique()
)

mapping_check[mapping_check > 1]

Series([], Name: Item, dtype: int64)

In [15]:
df.groupby(["Category", "Price Per Unit"])["Item"].nunique()

Category    Price Per Unit
Beverages   5.0               1
            6.5               1
            8.0               1
            9.5               1
            11.0              1
                             ..
Patisserie  35.0              1
            36.5              1
            38.0              1
            39.5              1
            41.0              1
Name: Item, Length: 200, dtype: int64

In [16]:
df_check = df.dropna(
    subset=[
        'Price Per Unit',
        'Quantity',
        'Total Spent',
        'Discount Applied'
    ]
).copy()

df_check['Expected_Total'] = (
    df_check['Price Per Unit'] *
    df_check['Quantity']
)

df_check['Discount_Amount'] = (
    df_check['Expected_Total'] -
    df_check['Total Spent']
)

df_check.groupby('Discount Applied')['Discount_Amount'].agg(
    ['count', 'min', 'max', 'mean', 'median']
)

                  count  min  max  mean  median
Discount Applied
False              3778  0.0  0.0   0.0     0.0
True               3801  0.0  0.0   0.0     0.0

In [17]:
nan_rows = df[df['Discount Applied'].isna()].copy()

known = df.dropna(
    subset=[
        'Item',
        'Category',
        'Price Per Unit',
        'Discount Applied'
    ]
)

pattern = (
    known
    .groupby(['Item', 'Category', 'Price Per Unit'])['Discount Applied']
    .agg(
        count='count',
        true_rate='mean'
    )
    .reset_index()
)

nan_analysis = nan_rows.merge(
    pattern,
    on=['Item', 'Category', 'Price Per Unit'],
    how='left'
)

nan_analysis[
    [
        'Item',
        'Category',
        'Price Per Unit',
        'count',
        'true_rate'
    ]
].head(30)

,Item,Category,Price Per Unit,count,true_rate
0,Item_16_BEV,Beverages,27.5,48.0,0.4375
1,NaN,Patisserie,NaN,NaN,NaN
2,Item_16_MILK,Milk Products,27.5,78.0,0.487179
3,NaN,Beverages,24.5,NaN,NaN
4,NaN,Milk Products,NaN,NaN,NaN
5,Item_7_BEV,Beverages,14.0,47.0,0.510638
6,NaN,Milk Products,NaN,NaN,NaN
7,Item_4_EHE,Electric household essentials,9.5,35.0,0.514286
8,Item_21_EHE,Electric household essentials,35.0,41.0,0.512195
9,NaN,Patisserie,23.0,NaN,NaN
10,Item_11_BEV,Beverages,20.0,38.0,0.5
11,Item_10_EHE,Electric household essentials,18.5,26.0,0.384615
12,Item_24_BUT,Butchers,39.5,28.0,0.464286
13,Item_8_BEV,Beverages,15.5,55.0,0.618182
14,Item_3_FOOD,Food,8.0,36.0,0.416667
15,Item_16_MILK,Milk Products,27.5,78.0,0.487179
16,Item_19_MILK,Milk Products,32.0,61.0,0.508197
17,Item_7_FUR,Furniture,14.0,34.0,0.588235
18,Item_16_FUR,Furniture,27.5,30.0,0.4
19,Item_2_BUT,Butchers,6.5,34.0,0.705882
20,Item_20_BUT,Butchers,33.5,65.0,0.338462
21,Item_4_BEV,Beverages,9.5,29.0,0.448276
22,Item_19_MILK,Milk Products,32.0,61.0,0.508197
23,Item_20_CEA,Computers and electric accessories,33.5,54.0,0.611111
24,Item_20_FOOD,Food,33.5,63.0,0.539683
25,Item_17_PAT,Patisserie,29.0,61.0,0.590164
26,Item_7_FOOD,Food,14.0,12.0,0.333333
27,Item_21_FUR,Furniture,35.0,44.0,0.613636
28,Item_8_MILK,Milk Products,15.5,49.0,0.428571
29,Item_4_PAT,Patisserie,9.5,47.0,0.446809

In [18]:
nan_analysis['inference'] = np.select(
    [
        (nan_analysis['count'] >= 5) & 
        (nan_analysis['true_rate'] >= 0.80),

        (nan_analysis['count'] >= 5) & 
        (nan_analysis['true_rate'] <= 0.20)
    ],
    [
        'True',
        'False'
    ],
    default='Unknown'
)

print(nan_analysis['inference'].value_counts())

inference
Unknown    4183
False        13
True          3
Name: count, dtype: int64

In [19]:
known = df.dropna(subset=['Item', 'Category', 'Price Per Unit', 'Discount Applied']).copy()
known['Discount Applied'] = known['Discount Applied'].astype(bool)   # هاد السطر يحل المشكلة

pattern_full = known.groupby(['Item', 'Category', 'Price Per Unit'])['Discount Applied'] \
    .agg(count='count', true_rate='mean')

pattern_full['true_rate'] = pattern_full['true_rate'].astype(float)  # تأكيد إضافي

print(pattern_full[pattern_full['count'] >= 5]['true_rate'].describe())
print(pattern_full[pattern_full['count'] >= 5]['true_rate'].round(1).value_counts().sort_index())

count    197.000000
mean       0.505334
std        0.102520
min        0.142857
25%        0.442623
50%        0.500000
75%        0.571429
max        1.000000
Name: true_rate, dtype: float64
true_rate
0.1     1
0.2     1
0.3    11
0.4    43
0.5    79
0.6    51
0.7    10
1.0     1
Name: count, dtype: int64

In [20]:
df['Transaction Date Parsed'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
invalid_dates = df[df['Transaction Date Parsed'].isna()]
print(f"Num of dirty dates: {len(invalid_dates)}")

Num of dirty dates: 0

In [21]:
text_cols = ['Category', 'Payment Method', 'Location', 'Item']
for col in text_cols:
    has_whitespace = df[col].dropna().apply(lambda x: x != x.strip()).sum()
    print(f"{col}: {has_whitespace} column with extra spaces")

Category: 0 column with extra spaces
Payment Method: 0 column with extra spaces
Location: 0 column with extra spaces
Item: 0 column with extra spaces

In [22]:
# Rules To clean the dataset : 
# 1- Columns Name should be in Snake Case way Transaction_ID, ....

# ### Data Type Rules

# - Transaction_ID → string
# - Customer_ID → string
# - Category → string/category
# - Item → string
# - Price_Per_Unit → float64
# - Quantity → integer
# - Total_Spent → float64
# - Payment_Method → string/category
# - Location → string/category
# - Transaction_Date → datetime64
# - Discount_Applied → boolean/NAN

# ### Missing Values Rules
# - Item : HashMap (Category, Price_Per_Unit) 
# - Price_Per_Unit : From Equation (Total_Spent / Quantity)
# - Quantity : From Equation (Total_Spent / Price_Per_Unit)
# - Total_Spent : From Equation (Quantity * Price_Per_Unit)
# -   Discount_Applied:
      # - Convert to nullable boolean (pandas 'boolean' dtype).
      # - Keep missing values as <NA> (unknown) — do not impute.
      # - Verified: discount status is randomly distributed per item 
      #   (mean true_rate ≈ 0.50, normal distribution around 0.5 across 
      #   197 items), confirming no reliable signal exists to infer 
      #   missing values from item, category, or price patterns.
      # - Confirmed the column has zero measurable effect on Price Per 
      #   Unit or Total Spent throughout the dataset.
# - Irrecoverable Rows Rule: Rows with two or more missing values among Price_Per_Unit, Quantity, and Total_Spent are considered irrecoverable and will be removed.
# if we had only quantity we can calculate the Price_Per_Unit and Total_Spent (we don't delete it)

# ### Outlier Rules

# - Detect statistical outliers using IQR.
# - Do not automatically remove outliers.
# - Retain outliers if they satisfy the business rules and valid value ranges.

# Validations :
# Column names / Data types -> should corrected directly 
# Missing values / Irrecoverable rows
# Total_Spent consistency (and check all of the values are not negative or quantity is integer)
# Value ranges / Categorical values
# validate_column_names, validate_data_types, validate_missing_values, validate_irrecoverable_rows,  validate_total_spent_consistency
# ,validate_value_ranges, validate_categorical_values, report_outliers_iqr(Price_Per_Unit), report_outliers_iqr(Total_Spent), validate_duplicates()
# validate_transaction_id_uniqueness(), validate_dates(), validate_item_mapping()

# Note : If two or more of the three financial columns are missing, the row is irrecoverable and will be removed.
# Note : (Category, Price_Per_Unit) → exactly one Item

In [23]:
import sys
import os

project_root = os.path.dirname(os.path.dirname(os.getcwd()))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.week3.cleaning import DataCleaner
from src.week3.validation import DataValidator

# 1. Clean the dataset
cleaner = DataCleaner(df)
df_clean = cleaner.clean_all()
print('\n')

print("=== Imputation Statistics ===")
for method, count in cleaner.imputation_stats.items():
    print(f"{method}: {count}")
print('\n')


# 2. Validate cleaned data
print("=== DATA QUALITY CHECK AFTER CLEANING ===")

validator = DataValidator(df_clean)
validation_results = validator.run_all_validations()

df_clean = df_clean.drop(columns=['transaction_date_parsed'])
print('\n')


# 3. Compare before and after
print("\n=== DATASET AFTER CLEANING ===")

print(f"Original Dimensions: {df.shape}")
print(f"Cleaned Dimensions: {df_clean.shape}")

print(
    f"Rows Removed: "
    f"{df.shape[0] - df_clean.shape[0]}"
)
print('\n')

# 4. Inspect final dataset
print("\n=== DATAFRAME INFO ===")
df_clean.info()

print("\n=== FIRST 5 ROWS ===")
display(df_clean.head())

=== Imputation Statistics ===
price_from_total_quantity: 609
price_from_item_mapping: 0
quantity_from_total_price: 0
quantity_rejected_non_integer: 0
total_from_quantity_price: 0
rows_removed_irrecoverable: 604
item_from_category_price_mapping: 609


=== DATA QUALITY CHECK AFTER CLEANING ===
=== DATA QUALITY VALIDATION REPORT ===
[Schema] Column Names Snake Case: PASS
[Schema] Data Types Validation: PASS
[Missing Data] Missing Values: PASS
discount_applied    3988
dtype: int64
[Missing Data] Irrecoverable Rows Check: PASS
[Duplicates] Exact Row Duplicates: PASS
[Duplicates] Transaction ID Uniqueness: PASS
[Financial] Total Spent Consistency: PASS
[Ranges] Value Range Validation: PASS
[Categorical] Categorical Values: PASS
  Invalid Payment Methods: 0
  Invalid Locations: 0
[Dates] Unparsable Dates: PASS
[Discount] Nullable Boolean Type: PASS
[Logic] Category + Price -> Item Mapping: PASS
[Outliers] price_per_unit: 0 statistical outliers detected (retained based on business rules).
[Outliers] total_spent: 60 statistical outliers detected (retained based on business rules).
========================================



=== DATASET AFTER CLEANING ===
Original Dimensions: (12575, 12)
Cleaned Dimensions: (11971, 11)
Rows Removed: 604



=== DATAFRAME INFO ===
<class 'pandas.DataFrame'>
Index: 11971 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    11971 non-null  string
 1   customer_id       11971 non-null  string
 2   category          11971 non-null  string
 3   item              11971 non-null  string
 4   price_per_unit    11971 non-null  float64
 5   quantity          11971 non-null  Int64
 6   total_spent       11971 non-null  float64
 7   payment_method    11971 non-null  string
 8   location          11971 non-null  string
 9   transaction_date  11971 non-null  datetime64[us]
 10  discount_applied  7983 non-null   boolean
dtypes: Int64(1), boolean(1), datetime64[us](1), float64(2), string(6)
memory usage: 1.0 MB

=== FIRST 5 ROWS ===

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,<NA>
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False

In [24]:
import os

output_dir = os.path.join(project_root, 'data', 'processed', 'week3')
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, 'retail_store_sales_cleaned.csv')
df_clean.to_csv(output_path, index=False)

print(f"Saved Successfully to {output_path}")

Saved Successfully to e:\DigitalFutureProjects\TrainingProjects\standalone-data-rag-assistant\data\processed\week3\retail_store_sales_cleaned.csv

In [25]:
# Normalize the column names of the original dataframe
df_before = df.copy()

df_before.columns = (
    df_before.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

# Compare missing values
missing_comparison = pd.DataFrame({
    'Before': df_before.isna().sum(),
    'After': df_clean.isna().sum()
})

missing_comparison['Recovered'] = (
    missing_comparison['Before'] - missing_comparison['After']
)

display(missing_comparison)


removed_mask = df_before[['price_per_unit', 'quantity', 'total_spent']].isna().sum(axis=1) >= 2
removed_rows = df_before[removed_mask]

for col in ['item', 'price_per_unit', 'quantity', 'total_spent', 'discount_applied']:
    print(f"{col}: Was empty in the row = {removed_rows[col].isna().sum()}")

                         Before   After  Recovered
category                      0     0.0        0.0
customer_id                   0     0.0        0.0
discount_applied           4199  3988.0      211.0
item                       1213     0.0     1213.0
location                      0     0.0        0.0
payment_method                0     0.0        0.0
price_per_unit              609     0.0      609.0
quantity                    604     0.0      604.0
total_spent                 604     0.0      604.0
transaction_date              0     0.0        0.0
transaction_date_parsed       0     NaN        NaN
transaction_id                0     0.0        0.0

item: Was empty in the row = 604
price_per_unit: Was empty in the row = 0
quantity: Was empty in the row = 604
total_spent: Was empty in the row = 604
discount_applied: Was empty in the row = 211

In [26]:
financial_cols = [
    'Price Per Unit',
    'Quantity',
    'Total Spent'
]

irrecoverable_mask = (
    df[financial_cols]
    .isna()
    .sum(axis=1) >= 2
)

print("Irrecoverable rows:", irrecoverable_mask.sum())

Irrecoverable rows: 604

In [27]:
print("=== Financial Missing Values After Cleaning ===")

print(
    df_clean[
        ['price_per_unit', 'quantity', 'total_spent']
    ].isna().sum()
)

=== Financial Missing Values After Cleaning ===
price_per_unit    0
quantity          0
total_spent       0
dtype: int64

In [28]:
print("=== FINAL DATASET SUMMARY ===")

print(f"Rows: {len(df_clean)}")
print(f"Columns: {len(df_clean.columns)}")

print("\nMissing values:")
print(df_clean.isna().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nDuplicate Transaction IDs:")
print(df_clean['transaction_id'].duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)

=== FINAL DATASET SUMMARY ===
Rows: 11971
Columns: 11

Missing values:
transaction_id         0
customer_id            0
category               0
item                   0
price_per_unit         0
quantity               0
total_spent            0
payment_method         0
location               0
transaction_date       0
discount_applied    3988
dtype: int64

Duplicate rows:
0

Duplicate Transaction IDs:
0

Data types:
transaction_id              string
customer_id                 string
category                    string
item                        string
price_per_unit             float64
quantity                     Int64
total_spent                float64
payment_method              string
location                    string
transaction_date    datetime64[us]
discount_applied           boolean
dtype: object

In [29]:
print("Before:", df['Discount Applied'].isna().sum())
print("After:", df_clean['discount_applied'].isna().sum())

print(
    df_clean['discount_applied']
    .value_counts(dropna=False)
)

Before: 4199
After: 3988
discount_applied
True     4019
<NA>     3988
False    3964
Name: count, dtype: Int64

In [30]:
removed_mask = df[['Price Per Unit', 'Quantity', 'Total Spent']].isna().sum(axis=1) >= 2
removed_rows = df[removed_mask]

print("من أصل الصفوف المحذوفة (604)، كم منها كان فيها:")
print(f"  Item مفقود: {removed_rows['Item'].isna().sum()}")
print(f"  Quantity مفقود: {removed_rows['Quantity'].isna().sum()}")
print(f"  Total Spent مفقود: {removed_rows['Total Spent'].isna().sum()}")

من أصل الصفوف المحذوفة (604)، كم منها كان فيها:
  Item مفقود: 604
  Quantity مفقود: 604
  Total Spent مفقود: 604